development: &development 
  adapter: postgresql
  encoding: unicode
  database: student-admin-api_development
  pool: 5
  username: postgres
  password: postgresqlserver
  timeout: 5000
  

test:
  adapter: postgresql
  encoding: unicode
  database: student-admin-api_test
  pool: 5
  username: postgres
  password: postgresqlserver
  timeout: 5000


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgresqlserver
  timeout: 5000
  database: <%= ENV['POSTGRES_DB'] %>
